//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_PTTKHTTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATHANG()
        {
            this.CHITIETHOADON = new HashSet<CHITIETHOADON>();
            this.TRONG1 = new HashSet<TRONG1>();
            this.NHACUNGCAP = new HashSet<NHACUNGCAP>();
        }
    
        public string MAMH { get; set; }
        public string MALMH { get; set; }
        public string TENMH { get; set; }
        public Nullable<int> SOLUONGTK { get; set; }
        public string VITRI { get; set; }
        public string MOTA { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public Nullable<decimal> GIAMUA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADON { get; set; }
        public virtual LOAIMATHANG LOAIMATHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRONG1> TRONG1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHACUNGCAP> NHACUNGCAP { get; set; }
    }
}
