//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT0720NguyenKhacDuyHung_63132095.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string MaSV { get; set; }
        public string HoSV { get; set; }
        public string TenSV { get; set; }
        public Nullable<System.DateTime> Ngsinh { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public string AnhSV { get; set; }
        public string Dchi { get; set; }
        public string Malop { get; set; }
    
        public virtual LOP LOP { get; set; }
    }
}
