//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiGKNguyenKhacDuyHung_63132095.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sach
    {
        [Required(ErrorMessage = "Mã sách không được để trống!")]
        public string masach { get; set; }
        [Required(ErrorMessage = "Tên sách không được để trống!")]
        public string tensach { get; set; }
        [Required(ErrorMessage = "Ngày xuất bản không được để trống!")]
        public DateTime ngayxuatban { get; set; }
        [Required(ErrorMessage = "Nhà xuất sách không được để trống!")]
        public string nhaxuatban { get; set; }
        public string anhbia { get; set; }
        public string maloaisach { get; set; }
    
        public virtual Loaisach Loaisach { get; set; }
    }
}
