//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHANG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CHITIETDONNHAPHANG
    {
        [DisplayName("Mã mặt hàng")]
        [Required(ErrorMessage = "Mã mặt hàng không được để trống")]
        public string MAMH { get; set; }

        [DisplayName("Mã đơn nhập hàng")]
        [Required(ErrorMessage = "Mã đơn nhập hàng không được để trống")]
        public string MADNH { get; set; }

        [DisplayName("Số lượng nhập hàng")]
        public Nullable<int> SOLUONGNH { get; set; }

        [DisplayFormat(DataFormatString = "{0:C0}")]
        public decimal? thanhtien { get; set; }
    
        public virtual DONNHAPHANG DONNHAPHANG { get; set; }
        public virtual MATHANG MATHANG { get; set; }
    }
}
