//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHANG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CHITIETHOADON
    {
        [Required]
        public string MAMH { get; set; }

        [Required]
        public string MAHD { get; set; }

        [Required]
        public int SOLUONGMH { get; set; }

        [DisplayFormat(DataFormatString = "{0:C0}")]
        [Required]
        public decimal thanhtien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual MATHANG MATHANG { get; set; }
    }
}
