//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHANG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DONNHAPHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONNHAPHANG()
        {
            this.CHITIETDONNHAPHANG = new HashSet<CHITIETDONNHAPHANG>();
        }

        [DisplayName("Mã đơn nhập hàng")]
        [Required(ErrorMessage = "Mã đơn nhập hàng không được để trống")]
        public string MADNH { get; set; }

        [DisplayName("Trạng thái")]
        public Nullable<bool> TRANGTHAI { get; set; }

        [DisplayName("Ngày lập đơn")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Required]
        public System.DateTime NGAYLAPDNH { get; set; }

        [DisplayName("Ngày xác nhận đơn")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> NGAYXACNHANDNH { get; set; }

        [DisplayFormat(DataFormatString = "{0:C0}")]
        public decimal? tongtiendnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONNHAPHANG> CHITIETDONNHAPHANG { get; set; }
    }
}
