//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHANG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LOAIMATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIMATHANG()
        {
            this.MATHANG = new HashSet<MATHANG>();
        }

        [DisplayName("Mã loại mặt hàng")]
        [Required(ErrorMessage = "Mã loại mặt hàng không được để trống")]
        public string MALMH { get; set; }

        [DisplayName("Tên loại mặt hàng")]
        [Required(ErrorMessage = "Tên loại mặt hàng không được để trống")]
        public string TENLMH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATHANG> MATHANG { get; set; }
    }
}
