//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHANG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATHANG()
        {
            this.CHITIETDONNHAPHANG = new HashSet<CHITIETDONNHAPHANG>();
            this.CHITIETNHACUNGCAP = new HashSet<CHITIETNHACUNGCAP>();
            this.CHITIETHOADON = new HashSet<CHITIETHOADON>();
        }

        [DisplayName("Mã mặt hàng")]
        [Required(ErrorMessage = "Mã mặt hàng không được để trống")]
        public string MAMH { get; set; }

        [Required(ErrorMessage = "Mã loại mặt hàng không được để trống")]
        public string MALMH { get; set; }

        [DisplayName("Tên mặt hàng")]
        [Required(ErrorMessage = "Tên loại mặt hàng không được để trống")]
        public string TENMH { get; set; }

        [DisplayName("SL tồn kho")]
        [Required(ErrorMessage = "Số lượng tồn không được để trống")]
        public int SOLUONGTK { get; set; }

        [DisplayName("Vị trí")]
        [Required(ErrorMessage = "Vị trí không được để trống")]
        public string VITRI { get; set; }

        [DisplayName("Mô tả")]
        public string MOTA { get; set; }

        [DisplayName("Giá bán")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        [Required(ErrorMessage = "Giá bán không được để trống")]
        public decimal GIABAN { get; set; }

        [DisplayName("Giá mua")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        [Required(ErrorMessage = "Giá mua không được để trống")]
        public decimal GIAMUA { get; set; }

        [DisplayName("Đơn vị")]
        [Required(ErrorMessage = "Đơn vị không được để trống")]
        public string DONVI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONNHAPHANG> CHITIETDONNHAPHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHACUNGCAP> CHITIETNHACUNGCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADON { get; set; }
        public virtual LOAIMATHANG LOAIMATHANG { get; set; }
    }
}
