// <auto-generated />
namespace BTT6_Nhom9_63CNTT4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddChucvu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddChucvu));
        
        string IMigrationMetadata.Id
        {
            get { return "202310240019506_AddChucvu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
