//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhanvien
    {
        public int manhanvien { get; set; }
        public string tennhanvien { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public decimal luong { get; set; }
        public string hinhanh { get; set; }
        public int maphong { get; set; }
    
        public virtual Phongban Phongban { get; set; }
    }
}
