//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANHANG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CHITIETNHACUNGCAP
    {
        [DisplayName("Mã mặt hàng")]
        [Required(ErrorMessage = "Mã mặt hàng không được để trống")]
        public string MAMH { get; set; }

        [DisplayName("Mã nhà cung cấp")]
        [Required(ErrorMessage = "Mã nhà cung cấp không được để trống")]
        public string MANCC { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual MATHANG MATHANG { get; set; }
    }
}
